import { Location, TimeSlot } from "@/types";

export const mockLocations: Location[] = [
  {
    id: "central-library",
    name: "Thư viện Trung tâm Đại học",
    description:
      "Trái tim của đời sống học thuật trong khuôn viên trường. Trải dài trên 5 tầng, Thư viện Trung tâm mang đến một môi trường học tập vô song với trang thiết bị hiện đại, các phòng đọc rộng rãi và quyền truy cập vào hàng ngàn tài liệu số. Hoàn hảo cho việc tự học tập trung hoặc các buổi nghiên cứu yên tĩnh.",
    address: "Số 1 Đại lộ Đại học, Khuôn viên chính",
    rating: 4.8,
    reviewCount: 312,
    noiseLevel: "quiet",
    purposes: ["solo", "recording"],
    availableSeats: 24,
    totalSeats: 120,
    amenities: ["WiFi", "Ổ cắm điện", "Điều hòa", "In ấn", "Tủ đồ", "Nước uống"],
    tags: ["24/7", "Miễn phí", "Khu yên tĩnh", "Buồng học"],
    images: [
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80",
      "https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80",
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "07:00", close: "23:00" },
      { day: "Thứ Bảy", open: "08:00", close: "20:00" },
      { day: "Chủ Nhật", open: "10:00", close: "18:00" },
    ],
    priceRange: "Miễn phí",
    distance: "0.1 km",
    reviews: [
      {
        id: "r1",
        author: "Minh Nguyễn",
        avatar: "MN",
        rating: 5,
        comment:
          "Tôi cực kỳ thích môi trường yên tĩnh ở đây. Các buồng học ở tầng 3 rất lý tưởng để tập trung làm việc sâu. Rất đề xuất!",
        date: "2026-04-28",
        purpose: "solo",
      },
      {
        id: "r2",
        author: "Sara Lee",
        avatar: "SL",
        rating: 5,
        comment:
          "Thư viện tốt nhất trong trường. Luôn tìm được chỗ ngồi và WiFi nhanh như chớp.",
        date: "2026-04-22",
        purpose: "solo",
      },
      {
        id: "r3",
        author: "Trần Đức",
        avatar: "TĐ",
        rating: 4,
        comment:
          "Tuyệt vời để ghi âm bài giảng và làm việc cá nhân. Tuy nhiên có chút đông đúc vào mùa thi.",
        date: "2026-04-15",
        purpose: "recording",
      },
    ],
  },
  {
    id: "innovation-hub-cafe",
    name: "Cà phê Sáng tạo Innovation Hub",
    description:
      "Một quán cà phê co-working sôi động nơi sự sáng tạo kết hợp với hiệu suất. Nổi bật với cà phê pha máy, internet tốc độ cao và bầu không khí nhộn nhịp thúc đẩy sự hợp tác. Thiết kế không gian mở và nội thất lắp ghép khiến nơi đây trở nên lý tưởng cho các dự án nhóm và cuộc họp thân mật.",
    address: "Số 42 Đường Khởi nghiệp, Khu Công nghệ",
    rating: 4.6,
    reviewCount: 187,
    noiseLevel: "medium",
    purposes: ["group", "solo", "meeting"],
    availableSeats: 8,
    totalSeats: 40,
    amenities: ["WiFi", "Ổ cắm điện", "Cà phê", "Bảng trắng", "Điều hòa"],
    tags: ["Cà phê", "Phù hợp nhóm", "Thân thiện", "Phòng đặt trước"],
    images: [
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80",
      "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "08:00", close: "22:00" },
      { day: "Thứ Bảy", open: "09:00", close: "22:00" },
      { day: "Chủ Nhật", open: "10:00", close: "20:00" },
    ],
    priceRange: "$",
    distance: "0.4 km",
    reviews: [
      {
        id: "r4",
        author: "Linh Phạm",
        avatar: "LP",
        rating: 5,
        comment:
          "Không gian tuyệt vời! Sự kết hợp giữa matcha latte và WiFi nhanh thật không có đối thủ. Nơi yêu thích của tôi để làm bài tập nhóm.",
        date: "2026-04-30",
        purpose: "group",
      },
      {
        id: "r5",
        author: "Alex Chen",
        avatar: "AC",
        rating: 4,
        comment:
          "Không gian tốt nhưng có thể hơi ồn vào giờ cao điểm. Nên đến trước 10 giờ sáng để có trải nghiệm tốt nhất.",
        date: "2026-04-18",
        purpose: "solo",
      },
    ],
  },
  {
    id: "quiet-corner",
    name: "Góc Yên Tĩnh",
    description:
      "Một viên ngọc ẩn mình bên trong Tòa nhà Nhân văn. Nhỏ nhắn, riêng tư và hoàn toàn im lặng — Góc Yên Tĩnh dành riêng cho những buổi học tập trung nghiêm túc. Không gọi điện thoại, chỉ nói khẽ. Trang bị đầy đủ các buồng cách âm và phong cách tối giản mang lại sự thư thái.",
    address: "Tòa nhà Nhân văn, Phòng 105, Khu phía Nam",
    rating: 4.9,
    reviewCount: 98,
    noiseLevel: "quiet",
    purposes: ["solo", "recording"],
    availableSeats: 6,
    totalSeats: 18,
    amenities: ["WiFi", "Ổ cắm điện", "Điều hòa", "Phòng cách âm"],
    tags: ["Siêu yên tĩnh", "Cách âm", "Buồng thu âm", "Miễn phí"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "09:00", close: "21:00" },
      { day: "Thứ Bảy", open: "10:00", close: "18:00" },
      { day: "Chủ Nhật", open: "Đóng cửa", close: "" },
    ],
    priceRange: "Miễn phí",
    distance: "0.6 km",
    reviews: [
      {
        id: "r6",
        author: "Hoa Trần",
        avatar: "HT",
        rating: 5,
        comment:
          "Các phòng cách âm thật tuyệt vời để ghi âm bài thuyết trình khóa luận. Chắc chắn phải ghé qua.",
        date: "2026-04-25",
        purpose: "recording",
      },
      {
        id: "r7",
        author: "James Wu",
        avatar: "JW",
        rating: 5,
        comment:
          "Không gian tập trung thuần khiết nhất mà tôi từng tìm thấy. Hoàn toàn không có bất kỳ phiền nhiễu nào.",
        date: "2026-04-10",
        purpose: "solo",
      },
    ],
  },
  {
    id: "campus-coworking-lab",
    name: "Phòng Co-working Campus Lab",
    description:
      "Được thiết kế dành riêng cho sinh viên hiện đại, Co-Working Lab mang đến không gian làm việc chuyên nghiệp chuẩn WeWork ngay tại trường học. Nhiều khu vực — tập trung, hợp tác và phòng họp — giúp bạn linh hoạt làm việc theo cách của mình. Đặt một phòng họp riêng hoặc chọn một bàn làm việc tự do.",
    address: "Tòa nhà Kỹ thuật, Tầng 2",
    rating: 4.5,
    reviewCount: 204,
    noiseLevel: "medium",
    purposes: ["meeting", "group", "solo"],
    availableSeats: 20,
    totalSeats: 60,
    amenities: [
      "WiFi",
      "Ổ cắm điện",
      "Điều hòa",
      "Máy chiếu",
      "Bảng trắng",
      "In ấn",
    ],
    tags: ["Phòng họp", "Bàn tự do", "Máy chiếu", "Miễn phí"],
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "07:30", close: "22:00" },
      { day: "Thứ Bảy", open: "09:00", close: "18:00" },
      { day: "Chủ Nhật", open: "Đóng cửa", close: "" },
    ],
    priceRange: "Miễn phí",
    distance: "0.2 km",
    reviews: [
      {
        id: "r8",
        author: "Nguyên Bảo",
        avatar: "NB",
        rating: 4,
        comment:
          "Các phòng họp rất tuyệt cho việc bảo vệ khóa luận và thuyết trình nhóm. Hãy đặt sớm nhé!",
        date: "2026-04-27",
        purpose: "meeting",
      },
      {
        id: "r9",
        author: "Emily Park",
        avatar: "EP",
        rating: 5,
        comment:
          "Hiện đại, sạch sẽ, dụng cụ hỗ trợ tốt. Máy chiếu trong phòng họp có chất lượng rất cao.",
        date: "2026-04-20",
        purpose: "group",
      },
    ],
  },
  {
    id: "brew-study-cafe",
    name: "Cà phê Brew & Study",
    description:
      "Where good coffee meets great study sessions. Brew & Study is a beloved off-campus café just a 5-minute walk from university gates. Known for their specialty brews, plant-based bites, and a welcoming atmosphere that keeps students coming back.",
    address: "Số 17 Phố Cao đẳng, Khu Đại học",
    rating: 4.4,
    reviewCount: 256,
    noiseLevel: "medium",
    purposes: ["solo", "group"],
    availableSeats: 12,
    totalSeats: 35,
    amenities: ["WiFi", "Ổ cắm điện", "Cà phê", "Đồ ăn", "Điều hòa"],
    tags: ["Ngoài trường", "Cà phê", "Đồ ăn", "Ấm cúng"],
    images: [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "07:00", close: "21:00" },
      { day: "Thứ Bảy", open: "08:00", close: "22:00" },
      { day: "Chủ Nhật", open: "09:00", close: "20:00" },
    ],
    priceRange: "$",
    distance: "0.5 km",
    reviews: [
      {
        id: "r10",
        author: "Thảo Vũ",
        avatar: "TV",
        rating: 4,
        comment:
          "Tuyệt vời để học tập thông thường. Cà phê ủ lạnh rất ngon và luôn có đủ ổ cắm điện.",
        date: "2026-04-29",
        purpose: "solo",
      },
      {
        id: "r11",
        author: "Kevin Zhao",
        avatar: "KZ",
        rating: 5,
        comment:
          "Không khí ấm cúng, nhân viên thân thiện. Đi kèm WiFi miễn phí chỉ với giá của một ly cà phê.",
        date: "2026-04-16",
        purpose: "group",
      },
    ],
  },
  {
    id: "rooftop-study-deck",
    name: "Sân thượng Học tập Rooftop Deck",
    description:
      "Đón nhận không khí trong lành và nguồn cảm hứng tại không gian học tập ngoài trời trên sân thượng của trường. Với tầm nhìn toàn cảnh thành phố, vùng phủ sóng Wi-Fi rộng và môi trường thư thái, Rooftop Deck là lựa chọn hoàn hảo cho những ai thích học dưới bầu trời. Hãy mang theo tai nghe nhé — trên này khá sôi động đấy!",
    address: "Trung tâm Sinh viên, Sân thượng Tầng 8",
    rating: 4.3,
    reviewCount: 143,
    noiseLevel: "noisy",
    purposes: ["group", "solo"],
    availableSeats: 15,
    totalSeats: 30,
    amenities: ["WiFi", "Ổ cắm điện", "Ngoài trời", "View thành phố"],
    tags: ["Ngoài trời", "View thành phố", "Thư giãn", "Miễn phí"],
    images: [
      "https://images.unsplash.com/photo-1545178803-4056771d60a3?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Chủ Nhật", open: "08:00", close: "20:00" },
      { day: "Tùy thuộc thời tiết", open: "", close: "" },
    ],
    priceRange: "Miễn phí",
    distance: "0.3 km",
    reviews: [
      {
        id: "r12",
        author: "Đức Anh",
        avatar: "ĐA",
        rating: 4,
        comment:
          "Tầm nhìn tuyệt đẹp, lý tưởng để thảo luận nhóm. Hãy đến sớm để vừa học vừa ngắm hoàng hôn!",
        date: "2026-04-26",
        purpose: "group",
      },
      {
        id: "r13",
        author: "Maria Santos",
        avatar: "MS",
        rating: 4,
        comment: "Trải nghiệm học tập ngoài trời độc đáo. Nhưng có thể hơi lộng gió!",
        date: "2026-04-14",
        purpose: "solo",
      },
    ],
  },
  {
    id: "graduate-research-room",
    name: "Phòng Nghiên cứu Sau đại học",
    description:
      "Dành riêng cho học viên sau đại học, phòng nghiên cứu cao cấp này cung cấp một không gian làm việc chuyên nghiệp, không gây xao nhãng để viết luận văn, nghiên cứu học thuật và họp riêng với giảng viên hướng dẫn. Có thể đặt theo các khung giờ 2 tiếng với quyền truy cập vào các cơ sở dữ liệu cao cấp.",
    address: "Viện Sau đại học, Phòng G01",
    rating: 4.7,
    reviewCount: 67,
    noiseLevel: "quiet",
    purposes: ["solo", "meeting"],
    availableSeats: 4,
    totalSeats: 12,
    amenities: [
      "WiFi",
      "Ổ cắm điện",
      "Điều hòa",
      "CSDL cao cấp",
      "Họp trực tuyến",
    ],
    tags: ["Sau đại học", "Cao cấp", "Nghiên cứu", "Gọi video"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&q=80",
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "09:00", close: "20:00" },
      { day: "Thứ Bảy", open: "10:00", close: "16:00" },
      { day: "Chủ Nhật", open: "Đóng cửa", close: "" },
    ],
    priceRange: "Miễn phí",
    distance: "0.7 km",
    reviews: [
      {
        id: "r14",
        author: "GS. Hằng Lê",
        avatar: "HL",
        rating: 5,
        comment:
          "Cơ sở vật chất đặc biệt tốt. Hệ thống hội nghị truyền hình đạt chuẩn chuyên nghiệp. Hoàn hảo cho việc phản biện luận văn trực tuyến.",
        date: "2026-04-23",
        purpose: "meeting",
      },
    ],
  },
  {
    id: "maker-space-studio",
    name: "Xưởng Sáng chế Maker Space",
    description:
      "Trung tâm sáng tạo phục vụ cho đổi mới, tạo mẫu và học tập thực hành. Maker Space trang bị sẵn máy in 3D, máy cắt laser, bàn kỹ thuật điện tử và các khu vực hợp tác mở. Bầu không khí sôi động và đầy năng lượng với những người đam mê chế tạo.",
    address: "Tòa nhà STEM, Tầng hầm",
    rating: 4.5,
    reviewCount: 178,
    noiseLevel: "noisy",
    purposes: ["group", "recording"],
    availableSeats: 18,
    totalSeats: 50,
    amenities: [
      "WiFi",
      "Ổ cắm điện",
      "Máy in 3D",
      "Thiết bị học tập",
      "Bảng trắng",
    ],
    tags: ["Chế tạo", "In 3D", "Sáng tạo", "Trang thiết bị"],
    images: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
      "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=800&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    ],
    openingHours: [
      { day: "Thứ Hai – Thứ Sáu", open: "10:00", close: "20:00" },
      { day: "Thứ Bảy", open: "11:00", close: "18:00" },
      { day: "Chủ Nhật", open: "Đóng cửa", close: "" },
    ],
    priceRange: "$",
    distance: "0.8 km",
    reviews: [
      {
        id: "r15",
        author: "Khoa Trần",
        avatar: "KT",
        rating: 5,
        comment:
          "Nơi tốt nhất cho các dự án phần cứng. Máy in 3D được bảo trì tốt và nhân viên cực kỳ nhiệt tình.",
        date: "2026-04-21",
        purpose: "group",
      },
      {
        id: "r16",
        author: "Zara Ahmed",
        avatar: "ZA",
        rating: 4,
        comment:
          "Ồn ào nhưng tràn đầy cảm hứng! Tuyệt vời cho các buổi sáng tạo. Đừng mong đợi sự yên tĩnh ở đây.",
        date: "2026-04-08",
        purpose: "recording",
      },
    ],
  },
];

export const mockTimeSlots: TimeSlot[] = [
  {
    id: "ts-1",
    label: "Sáng sớm",
    startTime: "07:00",
    endTime: "09:00",
    available: true,
  },
  {
    id: "ts-2",
    label: "Buổi sáng",
    startTime: "09:00",
    endTime: "11:00",
    available: true,
  },
  {
    id: "ts-3",
    label: "Cuối buổi sáng",
    startTime: "11:00",
    endTime: "13:00",
    available: false,
  },
  {
    id: "ts-4",
    label: "Buổi chiều",
    startTime: "13:00",
    endTime: "15:00",
    available: true,
  },
  {
    id: "ts-5",
    label: "Cuối buổi chiều",
    startTime: "15:00",
    endTime: "17:00",
    available: false,
  },
  {
    id: "ts-6",
    label: "Buổi tối",
    startTime: "17:00",
    endTime: "19:00",
    available: true,
  },
  {
    id: "ts-7",
    label: "Ban đêm",
    startTime: "19:00",
    endTime: "21:00",
    available: true,
  },
];

export function getLocationById(id: string): Location | undefined {
  return mockLocations.find((loc) => loc.id === id);
}
