import { Location, TimeSlot } from "@/types";

export const mockLocations: Location[] = [
  {
    id: "central-library",
    name: "Central University Library",
    description:
      "The heart of academic life on campus. Spread across 5 floors, the Central Library offers an unmatched studying environment with state-of-the-art facilities, vast reading halls, and access to thousands of digital resources. Perfect for focused solo study or quiet research sessions.",
    address: "1 University Ave, Main Campus",
    rating: 4.8,
    reviewCount: 312,
    noiseLevel: "quiet",
    purposes: ["solo", "recording"],
    availableSeats: 24,
    totalSeats: 120,
    amenities: ["WiFi", "Power Outlet", "AC", "Printing", "Lockers", "Water"],
    tags: ["24/7", "Free", "Quiet Zone", "Study Pods"],
    images: [
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80",
      "https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80",
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "07:00", close: "23:00" },
      { day: "Saturday", open: "08:00", close: "20:00" },
      { day: "Sunday", open: "10:00", close: "18:00" },
    ],
    priceRange: "Free",
    distance: "0.1 km",
    reviews: [
      {
        id: "r1",
        author: "Minh Nguyen",
        avatar: "MN",
        rating: 5,
        comment:
          "Absolutely love the quiet environment. The study pods on the 3rd floor are perfect for deep work. Highly recommend!",
        date: "2026-04-28",
        purpose: "solo",
      },
      {
        id: "r2",
        author: "Sara Lee",
        avatar: "SL",
        rating: 5,
        comment:
          "Best library on campus. Always find a seat and the WiFi is lightning fast.",
        date: "2026-04-22",
        purpose: "solo",
      },
      {
        id: "r3",
        author: "Tran Duc",
        avatar: "TD",
        rating: 4,
        comment:
          "Great for recording lectures and individual work. Gets a bit crowded during exam season though.",
        date: "2026-04-15",
        purpose: "recording",
      },
    ],
  },
  {
    id: "innovation-hub-cafe",
    name: "Innovation Hub Café",
    description:
      "A vibrant co-working café where creativity meets productivity. Featuring artisan coffee, high-speed internet, and a buzzing atmosphere that fuels collaboration. The open floor plan and modular furniture make it ideal for group projects and informal meetings.",
    address: "42 Innovation Drive, Tech Quarter",
    rating: 4.6,
    reviewCount: 187,
    noiseLevel: "medium",
    purposes: ["group", "solo", "meeting"],
    availableSeats: 8,
    totalSeats: 40,
    amenities: ["WiFi", "Power Outlet", "Coffee", "Whiteboard", "AC"],
    tags: ["Coffee", "Group Friendly", "Casual", "Bookable Rooms"],
    images: [
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80",
      "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "08:00", close: "22:00" },
      { day: "Saturday", open: "09:00", close: "22:00" },
      { day: "Sunday", open: "10:00", close: "20:00" },
    ],
    priceRange: "$",
    distance: "0.4 km",
    reviews: [
      {
        id: "r4",
        author: "Linh Pham",
        avatar: "LP",
        rating: 5,
        comment:
          "Amazing vibe! The matcha latte + fast WiFi combo is unbeatable. My go-to for group projects.",
        date: "2026-04-30",
        purpose: "group",
      },
      {
        id: "r5",
        author: "Alex Chen",
        avatar: "AC",
        rating: 4,
        comment:
          "Great space but can get loud during peak hours. Come before 10am for the best experience.",
        date: "2026-04-18",
        purpose: "solo",
      },
    ],
  },
  {
    id: "quiet-corner",
    name: "The Quiet Corner",
    description:
      "A hidden gem tucked inside the Humanities Building. Small, intimate, and absolutely silent — The Quiet Corner is reserved for serious focus sessions. No phone calls, hushed voices only. Complete with noise-cancelling booths and a calming minimal aesthetic.",
    address: "Humanities Bldg, Room 105, South Campus",
    rating: 4.9,
    reviewCount: 98,
    noiseLevel: "quiet",
    purposes: ["solo", "recording"],
    availableSeats: 6,
    totalSeats: 18,
    amenities: ["WiFi", "Power Outlet", "AC", "Soundproof Booths"],
    tags: ["Ultra Quiet", "Soundproof", "Recording Booths", "Free"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "09:00", close: "21:00" },
      { day: "Saturday", open: "10:00", close: "18:00" },
      { day: "Sunday", open: "Closed", close: "" },
    ],
    priceRange: "Free",
    distance: "0.6 km",
    reviews: [
      {
        id: "r6",
        author: "Hoa Tran",
        avatar: "HT",
        rating: 5,
        comment:
          "The soundproof booths are incredible for recording thesis presentations. An absolute must-visit.",
        date: "2026-04-25",
        purpose: "recording",
      },
      {
        id: "r7",
        author: "James Wu",
        avatar: "JW",
        rating: 5,
        comment:
          "Purest concentration space I've ever found. No distractions whatsoever.",
        date: "2026-04-10",
        purpose: "solo",
      },
    ],
  },
  {
    id: "campus-coworking-lab",
    name: "Campus Co-Working Lab",
    description:
      "Designed with the modern student in mind, the Co-Working Lab brings the best of WeWork-style spaces to campus. Multiple zones — focus, collaboration, and meeting rooms — give you the flexibility to work your way. Book a private meeting room or grab a hot desk.",
    address: "Engineering Tower, Floor 2",
    rating: 4.5,
    reviewCount: 204,
    noiseLevel: "medium",
    purposes: ["meeting", "group", "solo"],
    availableSeats: 20,
    totalSeats: 60,
    amenities: [
      "WiFi",
      "Power Outlet",
      "AC",
      "Projector",
      "Whiteboard",
      "Printing",
    ],
    tags: ["Meeting Rooms", "Hot Desks", "Projector", "Free"],
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "07:30", close: "22:00" },
      { day: "Saturday", open: "09:00", close: "18:00" },
      { day: "Sunday", open: "Closed", close: "" },
    ],
    priceRange: "Free",
    distance: "0.2 km",
    reviews: [
      {
        id: "r8",
        author: "Nguyen Bao",
        avatar: "NB",
        rating: 4,
        comment:
          "The meeting rooms are great for thesis defenses and team presentations. Book early!",
        date: "2026-04-27",
        purpose: "meeting",
      },
      {
        id: "r9",
        author: "Emily Park",
        avatar: "EP",
        rating: 5,
        comment:
          "Modern, clean, great tools. The projectors in meeting rooms are top quality.",
        date: "2026-04-20",
        purpose: "group",
      },
    ],
  },
  {
    id: "brew-study-cafe",
    name: "Brew & Study Café",
    description:
      "Where good coffee meets great study sessions. Brew & Study is a beloved off-campus café just a 5-minute walk from university gates. Known for their specialty brews, plant-based bites, and a welcoming atmosphere that keeps students coming back.",
    address: "17 College Street, University District",
    rating: 4.4,
    reviewCount: 256,
    noiseLevel: "medium",
    purposes: ["solo", "group"],
    availableSeats: 12,
    totalSeats: 35,
    amenities: ["WiFi", "Power Outlet", "Coffee", "Food", "AC"],
    tags: ["Off-Campus", "Coffee", "Food", "Cozy"],
    images: [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "07:00", close: "21:00" },
      { day: "Saturday", open: "08:00", close: "22:00" },
      { day: "Sunday", open: "09:00", close: "20:00" },
    ],
    priceRange: "$",
    distance: "0.5 km",
    reviews: [
      {
        id: "r10",
        author: "Thao Vu",
        avatar: "TV",
        rating: 4,
        comment:
          "Great for casual study. The cold brew is incredible and there are always enough outlets.",
        date: "2026-04-29",
        purpose: "solo",
      },
      {
        id: "r11",
        author: "Kevin Zhao",
        avatar: "KZ",
        rating: 5,
        comment:
          "Cozy atmosphere, friendly staff. Comes with free WiFi for the price of a coffee.",
        date: "2026-04-16",
        purpose: "group",
      },
    ],
  },
  {
    id: "rooftop-study-deck",
    name: "Rooftop Study Deck",
    description:
      "Get fresh air and inspiration at the university's open-air rooftop study space. With panoramic city views, Wi-Fi coverage, and a laid-back environment, the Rooftop Deck is perfect for those who prefer studying under the sky. Bring headphones — it's lively up here!",
    address: "Student Centre, Rooftop Level 8",
    rating: 4.3,
    reviewCount: 143,
    noiseLevel: "noisy",
    purposes: ["group", "solo"],
    availableSeats: 15,
    totalSeats: 30,
    amenities: ["WiFi", "Power Outlet", "Open Air", "City View"],
    tags: ["Outdoor", "City View", "Casual", "Free"],
    images: [
      "https://images.unsplash.com/photo-1545178803-4056771d60a3?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Sunday", open: "08:00", close: "20:00" },
      { day: "Weather permitting", open: "", close: "" },
    ],
    priceRange: "Free",
    distance: "0.3 km",
    reviews: [
      {
        id: "r12",
        author: "Duc Anh",
        avatar: "DA",
        rating: 4,
        comment:
          "Gorgeous view, great for group brainstorming. Get there early for sunset study sessions!",
        date: "2026-04-26",
        purpose: "group",
      },
      {
        id: "r13",
        author: "Maria Santos",
        avatar: "MS",
        rating: 4,
        comment: "Unique experience studying outdoors. Can be windy though!",
        date: "2026-04-14",
        purpose: "solo",
      },
    ],
  },
  {
    id: "graduate-research-room",
    name: "Graduate Research Room",
    description:
      "Exclusively for postgraduate students, this premium research room provides a professional, distraction-free workspace for thesis writing, academic research, and private meetings with supervisors. Bookable in 2-hour blocks with access to premium databases.",
    address: "Graduate School, Room G01",
    rating: 4.7,
    reviewCount: 67,
    noiseLevel: "quiet",
    purposes: ["solo", "meeting"],
    availableSeats: 4,
    totalSeats: 12,
    amenities: [
      "WiFi",
      "Power Outlet",
      "AC",
      "Premium DB Access",
      "Video Conferencing",
    ],
    tags: ["Postgrad Only", "Premium", "Research", "Video Call"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&q=80",
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "09:00", close: "20:00" },
      { day: "Saturday", open: "10:00", close: "16:00" },
      { day: "Sunday", open: "Closed", close: "" },
    ],
    priceRange: "Free",
    distance: "0.7 km",
    reviews: [
      {
        id: "r14",
        author: "Prof. Hang Le",
        avatar: "HL",
        rating: 5,
        comment:
          "Exceptional facility. The video conferencing setup is professional-grade. Perfect for online thesis reviews.",
        date: "2026-04-23",
        purpose: "meeting",
      },
    ],
  },
  {
    id: "maker-space-studio",
    name: "Maker Space Studio",
    description:
      "The creative hub for innovation, prototyping, and hands-on learning. The Maker Space features 3D printers, laser cutters, electronics benches, and open collaboration zones. Expect a lively, energetic atmosphere with fellow makers and tinkerers.",
    address: "STEM Building, Basement Level",
    rating: 4.5,
    reviewCount: 178,
    noiseLevel: "noisy",
    purposes: ["group", "recording"],
    availableSeats: 18,
    totalSeats: 50,
    amenities: [
      "WiFi",
      "Power Outlet",
      "3D Printer",
      "Equipment",
      "Whiteboard",
    ],
    tags: ["Maker", "3D Printing", "Creative", "Equipment"],
    images: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
      "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=800&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    ],
    openingHours: [
      { day: "Monday – Friday", open: "10:00", close: "20:00" },
      { day: "Saturday", open: "11:00", close: "18:00" },
      { day: "Sunday", open: "Closed", close: "" },
    ],
    priceRange: "$",
    distance: "0.8 km",
    reviews: [
      {
        id: "r15",
        author: "Khoa Tran",
        avatar: "KT",
        rating: 5,
        comment:
          "Best place for hardware projects. The 3D printers are well-maintained and staff are super helpful.",
        date: "2026-04-21",
        purpose: "group",
      },
      {
        id: "r16",
        author: "Zara Ahmed",
        avatar: "ZA",
        rating: 4,
        comment:
          "Loud but inspiring! Great for creative sessions. Don't expect silence here.",
        date: "2026-04-08",
        purpose: "recording",
      },
    ],
  },
];

export const mockTimeSlots: TimeSlot[] = [
  {
    id: "ts-1",
    label: "Early Morning",
    startTime: "07:00",
    endTime: "09:00",
    available: true,
  },
  {
    id: "ts-2",
    label: "Morning",
    startTime: "09:00",
    endTime: "11:00",
    available: true,
  },
  {
    id: "ts-3",
    label: "Late Morning",
    startTime: "11:00",
    endTime: "13:00",
    available: false,
  },
  {
    id: "ts-4",
    label: "Afternoon",
    startTime: "13:00",
    endTime: "15:00",
    available: true,
  },
  {
    id: "ts-5",
    label: "Late Afternoon",
    startTime: "15:00",
    endTime: "17:00",
    available: false,
  },
  {
    id: "ts-6",
    label: "Evening",
    startTime: "17:00",
    endTime: "19:00",
    available: true,
  },
  {
    id: "ts-7",
    label: "Night",
    startTime: "19:00",
    endTime: "21:00",
    available: true,
  },
];

export function getLocationById(id: string): Location | undefined {
  return mockLocations.find((loc) => loc.id === id);
}
